services:
  - type: worker
    name: abj-tutorial-bot
    runtime: python-3.11  
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.16

