services:
  - type: worker
    name: abj-tutorial-bot
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install --upgrade --force-reinstall --no-cache-dir python-telegram-bot==21.0 python-dotenv==1.0.0
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: MAIN_CHANNEL_ID
        sync: false
      - key: CONTACT_USERNAME
        sync: false
      - key: CONTACT_PHONE
        sync: false
      - key: BOT_USERNAME
        sync: false

